### ISSUE TITLE
frog$altitude is a factor

### ISSUE THREAD

**Issue by rpruim** [OI-Biostat/oi_biostat_data#2]
Is this intentional?  I'm wondering if there were commas in your original data source that caused the data to be converted to a string and from there to a factor, perhaps because of `read.csv()`?

**Comment by JulieVu** [comment]
This is intentional and reflects the coding used to produce Figure 1.40 in the text.

**Comment by rpruim** [comment]
Hmm.. Even if you wanted that figure in the book, I wouldn't recode the data that way.  

And Figure 1.40 is easy to misinterpret. It is set up to look like there is a numerical scale, but the distances between the numerical values are not consistent, so it is in fact an ordinal categorical scale where I can't tell the values for half of the categories.  (Also, was the elevation measured to the nearest cm?)

If you keep things this way, it might be worth an addendum in the help, which describes the variable as 

* Altitude of study site in meters above sea level.

That sounds quantitative.  You could append "coded as a factor" to make it clear that it is not.

My preference would be to convert the altitude to quantitative and have a separate factor for the site labels.

**Comment by rpruim** [comment]
Possible Fig 1.40 replacement.  (But there are many variations on this theme.)

![image](https://user-images.githubusercontent.com/722231/92511626-92212900-f1db-11ea-93f6-a639a800b7ba.png)

**Comment by JulieVu** [comment]
Thanks for the feedback! We will keep this in mind as we work on the second edition.
